# Generated by Django 6.0.2 on 2026-03-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estimated_value_oz',
        ),
    ]
